apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 8000
      targetPort: 8000